# Generated by Django 4.2.7 on 2023-11-29 08:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=100)),
                ('emplacement', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('classe_voyage', models.CharField(max_length=20)),
                ('tarifs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_destination', models.CharField(max_length=100)),
                ('coordonnees_geographiques', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hotel', models.CharField(max_length=100)),
                ('emplacement', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('categorie_etoiles', models.IntegerField()),
                ('tarifs_chambres', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_restaurant', models.CharField(max_length=100)),
                ('emplacement', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type_cuisine', models.CharField(max_length=50)),
                ('menu', models.TextField()),
                ('tarifs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
    ]
